project_id = "lcefelbzvtpgnelmdmwy"

[functions.rgpd-assistant]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = false

[functions.send-message-notification]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.send-rights-request-notification]
verify_jwt = false

[functions.send-client-welcome-email]
verify_jwt = false

[functions.send-audit-completion-email]
verify_jwt = false

[functions.resend-client-welcome-email]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.create-portal-session]
verify_jwt = false

[functions.payments-webhook]
verify_jwt = false
